{
 "title": "DipperNetwork Dashbord",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "singlestat",
   "description": "Height of the chain",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "tendermint_consensus_height" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "singlestat",
   "description": "Number of peers node's connected to\n\n(Need to change Threshold)",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "tendermint_p2p_peers" }
   ]
  },
  {
   "title": "Total Voting Power",
   "type": "singlestat",
   "description": "Total voting power of all validators",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power"
    }
   ]
  },
  {
   "title": "Consensus Rounds At Current Height",
   "type": "singlestat",
   "description": "Number of rounds",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "tendermint_consensus_rounds" }
   ]
  },
  {
   "title": "Transactions At Current Height",
   "type": "singlestat",
   "description": "Number of transactions",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "tendermint_consensus_num_txs" }
   ]
  },
  {
   "title": "Confirmed Transactions",
   "type": "singlestat",
   "description": "Total number of transactions committed",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "tendermint_consensus_total_txs" }
   ]
  },
  {
   "title": "Block Size (bytes)",
   "type": "singlestat",
   "description": "Block size in bytes",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes"
    }
   ]
  },
  {
   "title": "Block TIme (seconds)",
   "type": "graph",
   "description": "Time between this and last block (Block.Header.Time) in seconds",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds"
    }
   ]
  },
  {
   "title": "Total Voting Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "STEAK" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power"
    }
   ]
  },
  { "title": "Mempool Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Unconfirmed",
   "type": "singlestat",
   "description": "Number of uncommitted transactions",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "tendermint_mempool_size" }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "description": "Cumulative count",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "tendermint_mempool_failed_txs" }
   ]
  },
  {
   "title": "Rechecked",
   "type": "singlestat",
   "description": "Cumulative count",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_mempool_recheck_times"
    }
   ]
  },
  {
   "title": "Size (bytes)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_mempool_tx_size_bytes_count"
    }
   ]
  },
  { "title": "Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Online",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_validators-tendermint_consensus_missing_validators"
    }
   ]
  },
  {
   "title": "Missing",
   "type": "singlestat",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators"
    }
   ]
  },
  {
   "title": "Byzantine",
   "type": "singlestat",
   "description": "Number of validators who tried to double sign",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_byzantine_validators"
    }
   ]
  },
  {
   "title": "% of (Missing+Byzantine)",
   "type": "singlestat",
   "description": "Percentage of missing + byzantine validators",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((tendermint_consensus_byzantine_validators_power + tendermint_consensus_missing_validators_power) / tendermint_consensus_validators_power) * 100"
    }
   ]
  },
  {
   "title": "Voting Power of Missing",
   "type": "singlestat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators_power"
    }
   ]
  },
  {
   "title": "Voting Power of Byzantine",
   "type": "singlestat",
   "description": "Total voting power of the byzantine validators",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_byzantine_validators_power"
    }
   ]
  },
  {
   "title": "Missing Validators History",
   "type": "graph",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators"
    }
   ]
  }
 ]
}